cargo-features = ["strip"]

[workspace]
members = ["soter-core", "soter-cs", "soter-client", "soter-server", "soter-cert", "soter-stun", "soter-macros"]

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1
