[package]
name = "soter-cs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
rand_chacha = "*"
serde = { version = "*", features = ["derive"] }
soter-core = { path = "../soter-core" }
bincode = "*"
thiserror = "*"
