[package]
name = "soter-cs"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "*"
rand = "*"
rand_chacha = "*"
serde = "*"
serde-big-array = { version = "*", features = ["const-generics"] }
soter-core = { path = "../soter-core" }
bincode = "*"
thiserror = "*"
