[package]
name = "soter-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "*"
serde-big-array = { version = "*", features = ["const-generics"] }
serde_bytes = "*"
serde = { version = "*", features = ["derive"] }
